---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: saga
spec:
  encryptedData:
    .dockerconfigjson: AgCiK0XiDNAksrJoHFKozq/M7LVehrFzB1BaG9GCt0C+nPgn7xYa2b7YDIcr4DWnocJUUr5nF/WB2C9pEqYb2qXWGdLtNTqpgZuPvnzuFIOZXQ9sjL6TyDrnlvnKxbwsrvzBkA9wuS/MbU0bnXoWk4MPyqslNV43d0ov7pr/DvMbe2ECKVPm40EHhIO657OtLcZYI814BKuQTKYyViaplXF9czrhob+M6hb35otqawu5XqKbMN2K17situhSZUYUaVLzf47WReFNGdbT99gAhwmWBIhFJsHMFqAZRLNGbVDbI6nbAi6BaGqYfrQNgIuZZvt3UHNAfwJMzIq5Cpz81qESJnzSUWo/D0wantfypWf1zMg3gpSlpZ3E3Ij4d8fJyws/0jbvNU9NlrX2KpbDJEkwUBIRjpbvrbRGa25CBT9eQe73vKU8p7UNbWuhMltwqTRNUfSaFdeh8S57waCHusguWeI4MUK5vQbBWWUC9P2gnSoTkEDDBE9TfXwlLYTAD2lLk86q9oXZTJyehXnJq2j/QnT2meL3q9fCY4vFCKZny6llBqPSecb9pHmv/2enr2+xErkrI96erf75pa17zuUT1CPY/Aj++hJAJtadDtUk7+fm1Qr1biHBP14dU7Wj0BY/MnanVgiwVbNz1VqmyW0pkWMUnUo1xO0uzgWItGW/XQjjELDa52AZa/nuzauMMuU3ZZzPhwxn6heuWBWqfj0nFaamEbsl+RN4ObZ2AkbxcUtt2IAyOg15COgms01scICewTf3iFQKg3t6ab/bjdwWvwL2IHk+jkvzYPsG9BqdEj1FC9e5NIB5PnsMZhT/4ImhTaPm6MyUoa8CnQEZbxySylyY/vYwHd+qUopQXbaHg2TgPHJDTjompbK6Gwkfw6s9vSKepraXgL1TiELt7paIj2VqaNfh0aozTnG5cV/iw3gHAGowyQTSuY+2QQ44QI8R4agvdhe9Rg/j4zy+HjZ7c3o0Wcro/JSzoEA=
  template:
    metadata:
      name: ghcr-secret
      namespace: saga
    type: kubernetes.io/dockerconfigjson