---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: saga
spec:
  encryptedData:
    .dockerconfigjson: AgAgROhqCn6YR92s8yH33Bxx6c7uPVLZTHZWCgEkqNLNKGUS243tz1otB4lFNay9OCgwxpXRRjpbo9M8fsXfvdH4z+8y1LefLIfJOvqBBET+QzVp1iqOUb4RaDutmsCcCQul4LOen7sfT86WsF6Q/PZEWNXMPlYNC8vESUOvOhlS7PStwYj2Jdqam4NSMga8dzpPh1T7wYB9EHg5C7FG5+xRsYhtGbsvjLNdnXFByH71Yq5rb/O6vdRDq4e0lmUBlC3r+4tkPFdlBIdPowUAPQqt+LsXdWdPnEC4vCDQHfS/CJBe/ndV+471fk1iIu64RxptRngc5Xo1bmJRnZO+rZ0I43Uk/mslKuE/K52SJqgMVGNJAT0OXOQiXWcqpTAsxgMW8pt5vIbpdeFUD36T0ZxG315Gx5gq75JUSZnfqdIKfz4O/xZrD95f+2AN0pO/wo737GDAlvUsv0XKydeWsf9zbdWKRhWuU5H3XXviAEHlfYxc32LPxcwORqHXopAo9dGA8UuGTzNaManDxQI++/DREyiLPHA6U7y3pqPDUO1JeuOqExSYPxDQoHFtrjYYkOGiR9Q7Fs+dLPxAsTe7pZi+fhHn2huMdzmSz0WQHdCum7yC2yeEj+nZ+QAEBHpGul9DeEZ1JoO8x+08N22ttwKVHGFAhZ66CWBT+FMDfYMwkhYdpdFbbu/1Rgn2RPZO+Xl8JUaWaNs9AyB3jTyu2B0edtJtFUWRsjv0DndAtSrqxqSGxGJiyEKFA96v4hpnZPs1dPnUsdginlwEDXesReziHHpIFmo/EdbgmmI1izmBy8bNaXnwcWJa9E9iVeRfpQtnfy+8ryk7FHXGZs/GrvmX4jQ6sWyD3KmPONxdSvLLs1Ky7wbeHrPDufzY8bV2wiYonAgKZmQgJXvc9ugozvsV1nbGEGOY2VqqidsVI7aS4NZNuBIU9vrHOdm8NbeKypa9y9CZjBFUTYWPSTXvQui1PI6CgbtNL8a65y4=
  template:
    metadata:
      name: ghcr-secret
      namespace: saga
    type: kubernetes.io/dockerconfigjson