---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-superuser-creds
  namespace: saga
spec:
  encryptedData:
    password: AgAa2tPTQd48uGKh9ZV9s20n9LCybbPw1lD1QW7u/jINzZz4Rzlr3PyTybaCG06mfcOOSGMCZvlTwtK2cjzEUuKUwnZSn850DK3mGJuIyyz/J6QWUCiimnihgmpfoQVbWYLBKFa20q0cIy8jAyAjdxwZrvIvWNRscXDH4/ze17wVOd8NjtdwPWv6sOwKI7ef36CgzaanFfSYla985/k1OJJoZ34/o7XGxB5dNYhCb9eX62G1sZHtMNxFTSOyoH+ELTGF6rEziWTcG1XFg7xhl92FOpb7ilRHHx6CaQmLSYVo5mXZmGfC4ODAnmgj0JcGTQt19dSqQD7lubd1RLU9TqRJcNUsY/SBobeR8zChIgzRMSN1yEWrqWyJcOTTD4lZOg68XLTXGfUlvtSflLxgqIv2O16ULdJfTZrBeVg20fhO1fSCLXP0If8BxGfxXz6GliaxlyyY+xRSsxfmS3GmFBYIfn101OOirdJZgGGn5JtDLpHFug7R6IzsC88zm4/Z5gasy73wuq9mG8vkcHWLj8hlMPQOOkVBkdqgN0HtVP1IeRp/F81lzXMWvEH0UZL3qTaCndBvdZ0smW7rxoy4UvggikbpCSsxkoAU69zJBULW0Jw4wUB0bXIPtcdEYztHSC/2I6QWrlBSOBtlC6HTDPKIXAnv9TQnvBEfL49m5kGNPh5SliyMdKPELHflYv+xYcDvkzMZ
    username: AgASl6wJSc+VL896OLH5SmCE8t2dQjYHmb43F2a7I2WU0ZDVe+8diWkp/tSpWsUkBcmZ18kPMSqqfn8hZQTgUAfFosDi5BU0u57FMALl0eD7c8z1rPSJbRMkHJ5UnQtiTavCO3NH0Svsrvpb+pvi2wyLVcCgutm0Gf5HxAzYjLCUi4YgwyocMm22WnPJPj7amB4uDyDT+gXwWzO9V7ZunNrpIMXfYHRZiWD1UYHQGm1CE/GKLGzCNOv3Rmk/Zk7uyuvjOl229SsEzz2NyHTnmaVFbqtFTpAb7PAKL0FONES82QTg7HT1FbMCbw0fGUdTv7hBs+RFnKi2TaVdPqmsbfHROIf39OvzWlQS6nFZd1gIPBSVPPXoBiSJIFtXJLwXW3MKCnc5DitRlBd7HnMs3ffy7mpL5wi+KPozCp9EkPRdm8OQW70UcJjnne+uTLL+G3Ha8qY1pbdX9vgnwgJMYQBX/T476+CdlcEcKXtKTb1AS8Vg/TbrFGpDKWlUn9/9SvPjAVuMwFbhAS0GyAU6JjsRGIeOmyGEYl6YrvwrYbjjcFcmjgzaIOG1F5AnUXwFt5n3WyT8Kos1s0nErkvisXj7HWqNySphFkOg28+lKoOPKC/p1ZV17hmGnxzcNRLhqkH8Rma/qqXW1coAsboKGnc7bYWvVx1KBH9TS17ii2sWCtGYM07L/zJx464BEgcqba+7lUxcirGwAw==
  template:
    metadata:
      name: postgres-superuser-creds
      namespace: saga
    type: kubernetes.io/basic-auth