---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-creds
  namespace: saga
spec:
  encryptedData:
    RabbitMq__Password: AgB2nYsMsHWhzeTFGg//HLigKqep5R42DY5Z+ZL6noF9979ZBv0yHQYFypsc3MX/A8dD8+ihnxfCHd53OHks2p8M1qT3uuAL2mPgCARl6VM0Gy5ZxAMOakBdzW/iqbPcmeEQgFr1o6VdRkMYGaLNjxFWY7S3JFKiVU2Dhp1visaJV+LaQ0ovD1znnFfB5SEPhNjALbxyiY6Tc7lwe1/Ujphub5kg7bCDhYdf8EGo78XfW1wB0uIwE3QZ2WqhxO9Td/fZWDJh6VeX86SYANqeyFtrfHHjNcagAcNxj8qkfYPTQkwBi8sWyEygJP1Eu1itZp50ZSsYVBhGmNq3ScuxS8jynrjmNY++2pLa/XYQHQyfOMZYjyiTtbTOIbr6xDyVM/rFPrUDGCn7ewCEL9eROBQXn50OkFVrclJ/U6MzEHRLtNxrlZpS9B/fCacWuhruHQw8zeQEkejdwCLsvu1pMQW+34kxqiRrMBXasOMIzp3cwVfI88b22zrhxCvHa0pkaHT6FhAK/K+L+S1RaZ+tzzKktB3XG12SUdqcECcVXjS6X0LonLPo9Jn0MJICFOFlg6ulMDdl8enuM5tkbm8Qj8ZfAQiY87V+K2NSdZxnsCVWB9QlIP2RJweCW9CtF+mrbtxLoj+sPsiXT2oZqT8nQcmtSEATTVMKPtaXFWOM+baZQfw+pxG4Q///SCu2+T6y5QNJFugH
    RabbitMq__Username: AgAbYVF3dX1C5odKPXIeKqAN+t+B2b7bxW7Xc/5XjfWCBxA2por4xy4PrBqWtNaB3U1vMJRTzlWsNEzR4ZOlodv+/gjS+vLgfYCLVdwogQLGvp193FSZ1L3kdqPngTld9+tP7WPMWELHTRpagjoKqJ1ne89W5DP2FS9p7IrmvtyP5YlMWVphNKUs+Ao+KmfIJuFYHDgjpJR0idB4WnIbAKbzeXrw+kVdh17V9QJVRzK6d+to1FKFNh56KVonW1YaJNNE+CddBqgmh/Clv/LDZVdCWCxYGZI3li3XX3Dmk2/+ZOGdZZT55VmYieiU1RTkmUdktBGdrYuOtEaF801hE5NYmegO2mh8PrLB0u1XH1ipQ0vNlBRAibg8X7ZGqJmV5KY12b2FgNviniFq6Axe9JzBiXSL7p/uOylkpJvwUXpwTvUXhE6ZMUIVOdpyjaIhYrl7bRX3Bg+GqTQxGsNNA0opzdglTSxhOiLVgdlqg73v44KoH0w7Z1aHKlqdw2lPO4ZI2fxE9teaMrbEYIzb8B4cjVTWGo+f4HZVEuVdGBOb9IQPWYvdKsc5qZl0FSYQQCBZgDhIuycPDkr4BeA784Y/NIRwgmcptNNY/3PgoXEBCiZMaewtktz81z+i0CiyxCGAJ8O6qTb3g0n/x2dzVjr/NEiC6E/chL9gOP6zc4D2njV5NUDEw47iHCSN3EVZtvq1Jd2z
  template:
    metadata:
      name: rabbitmq-creds
      namespace: saga
    type: Opaque