---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-creds
  namespace: saga
spec:
  encryptedData:
    RabbitMq__Password: AgCcJptkQGhWWuNFISAvxlXoSH496TYMxYR+rA6p9XAucQ4cJKQSmFVqwmOHAjsOL70uiY2lYwipS8Be2s5568DRsDF00zH/qztPVqfDOx2ydD5+FnXoofT34zkOzRoDnzACn0uMOYZwg7v1F8EFw08yN/uALShL1TEdZazh9j76tHNhED7DAxJfFbtBvDNA1Yk0lXiXtNksU/VH0/SLEXoDCCxUuFE78nz3WpJenIQoSDkKXRoitr48Q2/AZE1toMuwXBugyp4IkXDlhejK7sDtioChavrb8jjJkH8ZmMysq9gtgo0b71poXYMuLJAF7yOhr7Mp7kNUncS6u/GKAG9gM7nOC4zoO/rFARUJ/tq5EJiwZNLd3jACk7Ynw5GZ3xjj4lJmkDYRE+PZmYo4l7zM0yS/NiWrtXjNluPmXHH4BPHGa5kYuiWcX7Yrj7IJb095NtT2saaKB0lvJVAmHqDSKqPX5FC3z0+PwMB7216xNeq+uzo73CiXOrylmOf8yy+RIdrmq7I/pPlfV7jxky3H+Fo8UxYW1qj7tq2CYJb2QWZ1p34Aq/pfKdblt6oHmUhCeb68sBgoGWBpnz+aVlZOjwxmwLRcIg8u87C4K4y2VyC+qvDE60P/8uz5/ONOtJkvEXRq3d0ec472C4Z3F7+OnXbq6/mlir1E1JGgqVUIjbQUOuGsnVsSW2UWLxTTpSrnCCuZMvhQOfjSRBd8MxhdjGPyeiRrMEqDKcWttiGVIg==
    RabbitMq__Username: AgAbpo+ZXiGdXPUefuvviy+PdjHn0gibwfFKLrGY8la2RLUSGx/AyOasrnOw0E+NpFpOHmUfaovPTYc9qBxjLKcV13y+ve+XhNdrTNkSKJ/Q9lwog+iNjbxaDQFgVVPmGje4nawvx6WvCL8zKhqkWMUMTalWvJSvbrVE37F1IilXMhqbmzaptSJgoROk8yIYK3JR44P0GqY5JPmBQrS9Ux8IhzHiWqc2ctISdXtZ4J2sv63vjjtcxP9P5SYzXz+AKykMkMG4twK0lwghwRqfuxejCleTq6pxD2H1OzSc0tjoeJ/dh372z1AaQdcbpb1oq+Votqz27wKpRAdUqCigvwA8n5/RattlpqeWWCcQjqp6b1uPDYEojJXYNbwEhxTTCdCCWKk7Omi2Kzy6atpKFO9776UDXu6H0LZilkDmWksJDqo6VaLwvRWkkEA1E+dDgSLynS9nyz2Y3hMxfATfKTSadtjPevMzK8bt1IdZQEYpzHldY71gQ50oL8cExXVO24tKtwtc6xgtxQrTCR/ogPvCkZmy63h/xKbqft1qz9T6q/WdbMR7zDXW/DDdS3shEKdUgR5C4Mh1ehTFm4Zl8+hEHy3Hx/dENwcPTOYEjEquip4P7piFutfdl3GLupvKQO2Y7/+tKiCY8RZHH37zvcK7yh5ymL56RrboUSs5OLsxRgX037AxmkJv2aX5b/07lj0PwQy/EhCn+yAi7K2GEBMb3ncdcJfZ/xxWltDkWrXz7w==
  template:
    metadata:
      name: rabbitmq-creds
      namespace: saga
    type: Opaque