---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-creds
  namespace: saga
spec:
  encryptedData:
    RabbitMq__Password: AgDQKqoGK3MydlfhQtAGTr1wS/06tSUp80bXk02RgSiQh8WKgMnADeNURiisn2Pt40VwFbnQhR2rQduzcMP+UXlZpeC44hF9MV66ERDZbSbDUe3GRN09msVmpYyEz7ot7pZYBd5InvwoCAYMQXishpx7gMutxqxomg9s1gCBKWl+3w4xEbSan+YQbaMupbpHjVp4ndBJXOEI9zpnN34FfrpC7q5umOVzY1q9ewIMn1O/NLqjW1ElWP5kJTx4I0DL0vLFpfHwBBUSQnOaGRhikTTytwpIrPa0eLUcxlB3RAPed+2lpgCbDLNB48UoXGLeK9tyScqGNbprmfAZaoFBinbT6XFBN3+8FRWg0DFJNoL2Ky3BdefOyd1Oxy8ZZUrQ0MlgSr3S5QIUx+LHwK9+mU0NXr74WSKqcI9MIyHZa6FSn1anT8qgQfEKnVCys+ZDN0k7RDSC+wVeucG2FDzGwKUoM+WXlUajNYkeJ4/qzFd7keisyxkjbo3ynR4Ba9/Kjzwo7PiGN1axNIfKQLnzhC8y+2FRRNttPrZJuGHYFwfdCn6wzb4XL0Gu/TRASWknj1AqN7FEn0G6BAy6KTHq/UaPiHPdLE+eXIyfceucBersPFyE64R6WMgEXNaHfR4qKPWn5JOD+TFCOHbPlnMjkipWmwXhhrfwFMpszs2FPNdprRyeY5Og3fiIqN45vkw6W/pCy07I
    RabbitMq__Username: AgBdFpQIbbiUkg+6mRiREMDJQDP/gsbB0CBS8gMvGvSh2Gg+AmjGrVSRDSVOZG3l/ope8dXou+3N6A06HS0x8FyRmfQrZ8UFg2tbc8LlcgRawcieBe2ma614BZokfuflNuCbT+Hc5rEeCzx6X5mKE5W9rzEd1vAL8ATbKnMSnZZ2PEVzqPNesOW4/f2Gm1GIOSqLYSJ16fNXFhtJjwPlzFya7xfxumljZS8NBpgkpKBlR8/NjnvfHONcXW6zyQV2K9c6mcBjHOKzSI/ykxxNo8dNI75gDDXWSicVcyZjR+5n6Rt991//YKOdHSLRyUPWgcZZ8jocK0+WUe1xPmxijO/yvT7my3W6b1il4+rM/RPLQJ3q/Nd/ZxrTpZb8Otbnq3zqNnzpBWUgoXOah6ZOcpgYFh0T6eEDkuBWU/ozMaeVAhOnQ7P/Ji+ELeFpWoaNonHm0v7R/eckiyrwiKhvWoC959ZT9VkGeyrxW3bRlb8BFi0OfM9mkmQuPTaSqJA8SI+aRJj0awzhi0Sd8DTw/MN3xW4nKLpDWaXrPcZpED1st6+TNYAfHDeEOQiwPPSfolWPh6Cx9Pi0YP+0wogxKDUzoIYKDe6SHpwxfOQ5T7yc9YjHjf405gXYrD3rA5I/tviK9Q0Zjchku+2epAYpI7FQAt5Y4ZwDGkCuyxZm6RYlRFApDF03OUCE2VF5pwUNQt3adQkY
  template:
    metadata:
      name: rabbitmq-creds
      namespace: saga
    type: Opaque