apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/just-vile/NT2204.CH201-gitops.git
    targetRevision: main
    path: charts/saga-service
    helm:
      releaseName: order-service
      valueFiles:
        - ../../environments/local/values-order-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: saga
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
